readme_index:
  enabled: false

remote_theme: pmarsceill/just-the-docs

title: Georgia
description: A dynamically generated fanart style theme for foobar2000.
# baseurl: "/georgia"
# url: "https://kbuffington.github.io"

permalink: pretty


# collections_dir: collections
# collections:
#   - screenshots
#   - showcase_sample
#   - showcase_user
#   - showcase_theme

aux_links:
  "View on GitHub":
    - "//github.com/kbuffington/georgia"

color_scheme: "dark"

footer_content: "Copyright &copy; 2018-2021"
